name 'nginx_cluster'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures nginx_cluster'
long_description 'Installs/Configures nginx_cluster'
version '0.1.0'
